version: "3.7"

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/docker.container/src
      - ./nodemon.json:/docker.container/nodemon.json
    container_name: docker-container
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev
